@extends('admin.layouts.app')

@section('title', 'CBL Regulatory Reports')
@section('page-title', 'Central Bank of Lesotho Compliance')

@section('content')
<div style="display:flex; flex-direction:column; gap:24px">
    <!-- Generation Filter -->
    <div class="card">
        <div class="card-hdr">
            <span class="card-title">Generate New Report</span>
        </div>
        <div style="padding: 20px">
            <form action="{{ route('admin.reports.cbl.generate') }}" method="GET">
                <div style="display:grid; grid-template-columns: 1fr 1fr 1fr 200px; gap:20px; align-items: end">
                    <div class="fg">
                        <label class="fl">Start Date</label>
                        <input type="date" name="start_date" class="fc" value="{{ request('start_date', now()->subMonth()->startOfMonth()->toDateString()) }}" required>
                    </div>
                    <div class="fg">
                        <label class="fl">End Date</label>
                        <input type="date" name="end_date" class="fc" value="{{ request('end_date', now()->subMonth()->endOfMonth()->toDateString()) }}" required>
                    </div>
                    <div class="fg">
                        <label class="fl">Segment Filter</label>
                        <select name="segment" class="fc">
                            <option value="ALL">All Segments</option>
                            <option value="Government">Government</option>
                            <option value="Private">Private</option>
                            <option value="SME">SME / Business</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-p" style="width:100%; justify-content:center; padding:12px">
                        <i class="bi bi-gear-wide-connected"></i> Generate Report
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- Archive List -->
    <div class="card">
        <div class="card-hdr">
            <span class="card-title">Regulatory Submission Archive</span>
            <a href="{{ route('admin.reports.cbl.complaints') }}" class="btn btn-sm btn-o">Complaints Register</a>
        </div>
        <div style="overflow-x:auto">
            <table class="dt">
                <thead>
                    <tr>
                        <th>Reporting Period</th>
                        <th>Generated At</th>
                        <th>Generated By</th>
                        <th>Status</th>
                        <th style="text-align:right">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($archives as $archive)
                    <tr>
                        <td>
                            <div style="font-weight:700; color:var(--p)">{{ $archive->report_period }}</div>
                            <div class="muted" style="font-size:11px">Hash: {{ substr($archive->data_hash, 0, 8) }}...</div>
                        </td>
                        <td>{{ $archive->generated_at->format('d M Y, H:i') }}</td>
                        <td>{{ $archive->generator->name }}</td>
                        <td><span class="badge bok">VALIDATED</span></td>
                        <td style="text-align:right">
                            <a href="{{ route('admin.reports.cbl.view-archive', $archive->id) }}" class="btn btn-sm btn-o">View Details</a>
                        </td>
                    </tr>
                    @endforeach
                    @if($archives->isEmpty())
                    <tr>
                        <td colspan="5" class="empty" style="padding: 60px">
                            <i class="bi bi-folder-x"></i>
                            <p>No archived reports yet. Generate your first regulatory report above.</p>
                        </td>
                    </tr>
                    @endif
                </tbody>
            </table>
        </div>
        @if($archives->hasPages())
            <div style="padding:15px; border-top:1px solid var(--border)">{{ $archives->links() }}</div>
        @endif
    </div>

    <!-- Compliance Checklist -->
    <div class="g3">
        <div class="card" style="border-left: 4px solid var(--p)">
            <div style="padding: 20px">
                <div style="display:flex; align-items:center; gap:12px; margin-bottom:10px">
                    <div style="width:36px; height:36px; background:var(--bg); border-radius:50%; display:flex; align-items:center; justify-content:center; color:var(--p)">
                        <i class="bi bi-shield-check"></i>
                    </div>
                    <div style="font-weight:700">Audit Ready</div>
                </div>
                <p class="muted" style="font-size:12px">Every generated report is archived with a full data snapshot to ensure regulatory audit traceability.</p>
            </div>
        </div>
        <div class="card" style="border-left: 4px solid var(--ok)">
            <div style="padding: 20px">
                <div style="display:flex; align-items:center; gap:12px; margin-bottom:10px">
                    <div style="width:36px; height:36px; background:var(--bg); border-radius:50%; display:flex; align-items:center; justify-content:center; color:var(--ok)">
                        <i class="bi bi-calculator"></i>
                    </div>
                    <div style="font-weight:700">Live Computations</div>
                </div>
                <p class="muted" style="font-size:12px">Zero manual overrides. All figures are computed directly from live transactional data to maintain integrity.</p>
            </div>
        </div>
        <div class="card" style="border-left: 4px solid var(--warn)">
            <div style="padding: 20px">
                <div style="display:flex; align-items:center; gap:12px; margin-bottom:10px">
                    <div style="width:36px; height:36px; background:var(--bg); border-radius:50%; display:flex; align-items:center; justify-content:center; color:var(--warn)">
                        <i class="bi bi-exclamation-triangle"></i>
                    </div>
                    <div style="font-weight:700">Validation Gate</div>
                </div>
                <p class="muted" style="font-size:12px">Exports are locked until all 10 regulatory reconciliation checks pass. Ensuring zero reporting errors.</p>
            </div>
        </div>
    </div>
</div>
@endsection
