<?php
use Illuminate\Support\Facades\Facade;
return [
    "name"=>env("APP_NAME","LoanPlatform"),
    "env"=>env("APP_ENV","production"),
    "logo"=>env("APP_LOGO", "storage/video/logo.webp"),
    "background_video"=>env("APP_BACKGROUND_VIDEO", "storage/video/mixkit-top-view-of-financial-accounting-with-coins-and-glasses-33435-medium.mp4"),
    "debug"=>(bool)env("APP_DEBUG",false),
    "url"=>env("APP_URL","http://localhost"),
    "timezone"=>"Africa/Maseru",
    "locale"=>"en",
    "fallback_locale"=>"en",
    "faker_locale"=>"en_US",
    "key"=>env("APP_KEY"),
    "cipher"=>"AES-256-CBC",
    "providers"=>[
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        //Barryvdh\DomPDF\ServiceProvider::class,
        App\Providers\AppServiceProvider::class,
    ],
    "aliases"=>Facade::defaultAliases()->merge([
        "PDF"=>Barryvdh\DomPDF\Facade\Pdf::class,
    ])->toArray(),
];
